name: Trigger auto deployment for cwp-site

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cwp-site-AutoDeployTrigger-1ca00f5b-70ac-463d-9b57-1d9541b250af.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CWPSITE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CWPSITE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CWPSITE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.CWPSITE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CWPSITE_REGISTRY_PASSWORD }}
          containerAppName: cwp-site
          resourceGroup: CWP_Group
          imageToBuild: registry.hub.docker.com/cwp-site:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


